INSERT INTO UIText (version, key, value, locale) VALUES (0, 'text.hello', 'Hejsan', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'text.hello', 'Hello', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'home.title.tooltip', 'Det här är en översiktssida', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'home.title.tooltip', 'First page dashboard style', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.settings.textedit.open', 'Öppna textändring', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.settings.textedit.open', 'Open text edit', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.settings.textedit.close', 'Stäng textändring', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.settings.textedit.close', 'Close text edit', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.settings.highcontrast', 'Högkontrastläge', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.settings.highcontrast', 'High contrast mode', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.title', 'UI-Text', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.title', 'UI-Text', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.todo.title', 'Att göra', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.todo.title', 'Todo', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.settings.title', 'Inställningar', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.settings.title', 'Settings', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.language.title', 'Språk', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.language.title', 'Language', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.language.swedish', 'Svenska', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.language.swedish', 'Swedish', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.language.english', 'Engelska', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'topbar.language.english', 'English', 'en');

INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.home', 'Översikt', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.home', 'Dashboard', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.profile.account', 'Profil', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.profile.account', 'Profile', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.profile.logout', 'Logga ut', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.profile.logout', 'Logout', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.uitexts', 'UItexter', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.uitexts', 'UItexter', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.examples', 'Exempel', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.examples', 'Examples', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.example1', 'Exempelsida 1', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.example1', 'Example page 1', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.texts', 'Texter', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.texts', 'Texts', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.standardtexts', 'Standardtexter', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.standardtexts', 'Standard texts', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.organization', 'Organisation', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.organization', 'Organization', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.users', 'Användare', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.users', 'Users', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.system', 'System', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.system', 'System', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.search', 'Sök', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.search', 'Search', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.search.planer', 'Planer', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.search.planer', 'Plans', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.search.information', 'Information', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.search.information', 'Information', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.search.tillfalle', 'Tillfälle', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.search.tillfalle', 'Moment', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.planer', 'Planer', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.planer', 'Plans', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.information', 'Information', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'sidebar.link.information', 'Information', 'en');


INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.uitexter.title', 'UI-texter', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.uitexter.title', 'UI-texts', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.uitexter.panel.textlist.header', 'Information om texter', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.uitexter.panel.textlist.header', 'List of text', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.uitexter.panel.textlist.table.key', 'Nyckel', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.uitexter.panel.textlist.table.key', 'Key', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.uitexter.panel.textlist.table.value', 'Text', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.uitexter.panel.textlist.table.value', 'Text', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.uitexter.panel.textlist.table.locale', 'Språk', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.uitexter.panel.textlist.table.locale', 'Language', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.planer.title', 'Planer', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.planer.title', 'Plans', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.planer.nyplan', 'Ny plan', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.planer.nyplan', 'New plan', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.planer.plan.historik', 'Historik', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.planer.plan.historik', 'History', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.planer.plan.protokoll', 'Protokoll', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.planer.plan.protokoll', 'Protocol', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.planer.plan.litteraturlista', 'Litteraturlista', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.planer.plan.litteraturlista', 'Lit. List', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.planer.plan.pdf', 'Pdf', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.planer.plan.pdf', 'Pdf', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.planer.plan.deltagare', 'Deltagare', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.planer.plan.deltagare', 'Participant', 'en');

INSERT INTO UIText (version, key, value, locale) VALUES (0, 'global.lorem.ipsum', 'Suspendisse potenti. Nunc at maximus justo. Praesent faucibus, lacus at tempor efficitur, lectus lacus placerat augue, quis vestibulum dolor ligula at arcu. Nulla sed ante ex. Aenean sollicitudin placerat cursus. Nunc ultricies massa eget mattis vestibulum. Nam lorem sem, cursus vel finibus a, varius nec dui.', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'global.lorem.ipsum', 'Suspendisse potenti. Nunc at maximus justo. Praesent faucibus, lacus at tempor efficitur, lectus lacus placerat augue, quis vestibulum dolor ligula at arcu. Nulla sed ante ex. Aenean sollicitudin placerat cursus. Nunc ultricies massa eget mattis vestibulum. Nam lorem sem, cursus vel finibus a, varius nec dui.', 'en');

INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.sample.one', 'Exempelsida 1', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'page.sample.one', 'Example page 1', 'en');

INSERT INTO UIText (version, key, value, locale) VALUES (0, 'component.infobox.detail', 'Detaljer', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'component.infobox.detail', 'Details', 'en');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'component.outputentry.valuemissing', '-- värde saknas --', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'component.outputentry.valuemissing', '-- value missing --', 'en');

INSERT INTO UIText (version, key, value, locale) VALUES (0, 'component.contentheader.crumb.home', 'Hem', 'sv');
INSERT INTO UIText (version, key, value, locale) VALUES (0, 'component.contentheader.crumb.home', 'Home', 'en');